export const useHomeActive = () => useState<boolean>('active', () => true)
export const useAnalyticsActive = () => useState<boolean>('analytics', () => false)
export const useSchedulesActive = () => useState<boolean>('schedules', () => false)
export const useCoursesActive = () => useState<boolean>('courses', () => false)
export const useToolsActive = () => useState<boolean>('tools', () => false)
export const useSettingsActive = () => useState<boolean>('settings', () => false)